---
- name: Start/Stop Linux Service
  hosts: all
  tasks:
    - name: Start {{ service_name }} Service
      service:
        name: "{{ service_name }}"
        state: started
      when: service_state == "Start"
    - name: Stop {{ service_name }} Service
      service:
        name: "{{ service_name }}"
        state: stopped
      when: service_state == "Stop"
    - name: Restart {{ service_name }} Service
      service:
        name: "{{ service_name }}"
        state: restarted
      when: service_state == "Restart"