---
- name: Windows | Add User
  hosts: all
  tasks:
    - name: Add User to Active Directory
      community.windows.win_domain_user:
        name: "{{  user_name  }}"
        firstname: "{{  user_firstname  }}"
        surname: "{{  user_lastname  }}"
        # company: "{{  user_company  }}"
        password: "{{  user_password  }}"
        # state: present
        # groups:
        #   - Domain Admins
        # street: 123 4th St.
        # city: Sometown
        # state_province: IN
        # postal_code: 12345
        # country: US
        # attributes:
        #   telephoneNumber: 555-123456